### ISSUE TITLE
Exception fires after running cucumber features on rails 5

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#222]
Output:
`rake cucumber`
... tests passing ...
13 scenarios (13 passed)
67 steps (67 passed)
0m5.834s
<details>
<summary>

Traceback</summary>

/Users/mason/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:57:in `plugin_rails_options': invalid option: --profile (OptionParser::InvalidOption)
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:200:in`block (2 levels) in process_args'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:198:in `each'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:198:in`block in process_args'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:168:in `new'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:168:in`process_args'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:122:in `run'
    from /Users/mason/.rvm/gems/ruby-2.3.1/gems/minitest-5.9.0/lib/minitest.rb:62:in`block in autorun'
</details>

**Comment by ajm188** [comment]
I think I found a solution. [See this](https://github.com/cucumber/multi_test/pull/2#issuecomment-21863459)
